# Generated by Django 3.0.11 on 2020-12-05 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d/')),
                ('country', models.CharField(max_length=200)),
                ('prep_time', models.IntegerField()),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('ingredients', models.TextField()),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('diet', models.ForeignKey(on_delete=models.SET('None'), related_name='recipes_in_diet', to='recipes.Diet')),
                ('region', models.ForeignKey(on_delete=models.SET('None'), related_name='recipes_from_region', to='recipes.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_created', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='recipes_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
