# Generated by Django 3.0.11 on 2021-02-18 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='created',
            field=models.DateField(db_index=True, default=datetime.datetime.now),
        ),
    ]
