# Generated by Django 3.0.11 on 2021-02-19 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210218_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='template',
            field=models.ImageField(blank=True, upload_to='cookbook/created/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cookbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_in_cookbook', to='recipes.CookBook'),
        ),
    ]
