# Generated by Django 3.0.11 on 2021-02-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210219_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
