# Generated by Django 3.0.11 on 2021-02-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210219_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='picture',
            field=models.ImageField(upload_to='cookbook/pictures/%Y/%m/%d/'),
        ),
    ]
